### ISSUE TITLE
missing icons and sets

### ISSUE THREAD

**Issue by davidysoards** [iconify/website#20]
Is this the best place to report such problems? If not let me know, or I would also be willing to help fix with a bit of guidance.

1. Feather Icons by Cole Bemis (a quite popular set) is available at http://icon-sets.iconify.design/feather/ but can not be found via filter on the Browse Icon Sets page. Feather Icon (singular, and less known) is shown.
<img width="1032" alt="Screenshot 2023-11-20 at 2 31 36 PM" src="https://github.com/iconify/website/assets/26875701/b76bcdc6-9997-4959-8172-07c60510c1fc">

2. While browsing the Majesticons set, I found several missing, specifically `check`, `check-line`, `check-circle`, and `check-circle-line`, even though they are available for use and can be seen here: https://github.com/iconify/icon-sets/blob/master/json/majesticons.json
<img width="1025" alt="Screenshot 2023-11-20 at 2 41 00 PM" src="https://github.com/iconify/website/assets/26875701/e67533eb-bb46-4ff1-9b8d-9c4eb9919a3b">

**Comment by cyberalien** [comment]
This is the correct place, thanks for reporting!

1. Feather Icons is available as Lucide: https://icon-sets.iconify.design/lucide/

Original icon set is marked as hidden to avoid content duplication. It has not been maintained for many years until recently and all icons are available in Lucide set.

Though there is a bug: when typing exact name or prefix of a hidden icon set in filter, it should show up. It is fixed in new version of website.

2. Those icons are marked as hidden, so they aren't visible when browsing. They were removed from source icon set for some reason, but in Iconify icons are never removed, they are still in json files but marked as hidden to avoid breaking stuff for users that rely on those icons.

Probably should treat them the same way as hidden icon sets: show them when exact match is typed. It won't be fixed on current website, but do need to test it on new website.

**Comment by davidysoards** [comment]
Oh cool. Lucide looks like a great project! I love Feather but it was very limited.
I can only assume Majesticons is trying to encourage people to purchase the paid version by removing something as essential as a checkmark from the free set. 

> they are still in json files but marked as hidden to avoid breaking stuff for users that rely on those icons.

good practice. makes sense.

> Probably should treat them the same way as hidden icon sets: show them when exact match is typed

I like this suggestion.

Thanks for the quick response and for helping maintain this fantastic project!
