### ISSUE TITLE
icon-sets website is broken

### ISSUE THREAD

**Issue by codenomnom** [iconify/website#32]
I'm sorry if this isn't the most appropriate place to create an issue, but I couldn't find better.

The website https://icon-sets.iconify.design/ is broken. Icons' search box appears only on _some_ inner pages. Filtering doesn't work.

I'm guessing there is/was some migration? Some of the Nuxt js files cannot be loaded and parts of the sites are completely broken.
![Screenshot 2024-12-16 114324](https://github.com/user-attachments/assets/457e739b-ddde-4372-ab75-e6ff13da49ff)
![Screenshot 2024-12-16 114414](https://github.com/user-attachments/assets/4a2bb4a5-8008-4083-a6d9-7cedb65845f3)

**Comment by cyberalien** [comment]
Thanks for reporting!

Fixed by purging cache. Old page was cached linking to resources that no longer exist.

Not sure why this happened, deployment is supposed to keep scripts from previous deployment to avoid exactly this scenario, so something went wrong in today's update. I'll investigate and fix it.

**Comment by cyberalien** [comment]
Actually, it wasn't a deployment issue or cache issue, but a server issue. Experiencing weird problems with one server that I cannot explain. Switched website to another server while trying to figure out why Nuxt on one specific server returns 404 for static assets that do exist, but works fine on other server.

Thanks a lot for report!
